apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mfti-course
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-mfti-course
